$out_dir = 'aux';
$pdflatex = 'lualatex -synctex=1 -interaction=nonstopmode'; # for fontspec package, e.g. Futura font
$pdf_mode = 1;
@default_files = ('example.tex');
ensure_path('TEXINPUTS', '../');